version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.1.3

workflows:
  build_and_push:
    jobs:
      - azure-acr/build-and-push-image:
          azure-username: AZURE_USERNAME
          azure-password: AZURE_PASSWORD
          registry-name: $REGISTRY_NAME
          login-server-name: $LOGIN_SERVER_NAME
          repo: $REPO
